### ISSUE TITLE
hf_load_dataset() not working for local csv

### ISSUE THREAD

**Issue by samterfa** [farach/huggingfaceR#32]
This code should ideally work based on [this documentation](https://huggingface.co/docs/datasets/loading): `hf_load_dataset("csv", data_files = "iris.csv")`. However, it fails on this line of datasets.R:
`dataset_base <- reticulate::py$load_dataset(dataset)`. Moving `dataset_base <- reticulate::py$load_dataset(dataset)` further down in the code to where `dataset_base` is used would fix this issue but I wasn't sure if it's placement was important for something else or if other refactoring would make sense.

**Comment by jpcompartir** [comment]
Perhaps splitting the function into two -  

1. local dataset (but is it just easier to use pre-existing read_ functions?)  
2. directly from The Hub 

the current load_dataset function should cache any downloaded datasets I think?
