### ISSUE TITLE
Check Out Happy Transformer

### ISSUE THREAD

**Issue by samterfa** [farach/huggingfaceR#6]
Happy Transformer is a Python Package that simplifies loading Huggingface models, fine tuning them, and evaluating them. This is probably better code to build off of than the transformers package itself. It's worth investigating anyway.

**Comment by farach** [comment]
Hey @samterfa! I got the chance to check out the Happy Transformer package, thanks for passing along. Very cool!

**Comment by samterfa** [comment]
Moved to [discussion](https://github.com/farach/huggingfaceR/discussions/10).
